# -*- coding: utf-8 -*-
"""Emit the LaTeX table bodies of Section 5 straight from the experiment CSVs.

Every number quoted in the paper's experimental section comes from here, so a
re-run of the batch followed by a re-run of this script updates the paper
without anybody retyping a figure.  The fragments are \\input{} from paper.tex
and contain table *bodies* only: the surrounding tabular, caption and label stay
in the paper where they can be read alongside the prose.

    cd clbs && py -m tools.export_experiments --runs p3 lowmid --gen-runs gen100
    cd paper01_new/tab && py gen_tables.py
"""
from __future__ import annotations

import csv
import os
import statistics as st
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
CLBS = os.path.join(ROOT, "clbs")
DATA = os.path.join(CLBS, "experiments")
if CLBS not in sys.path:
    sys.path.insert(0, CLBS)

from algorithm.stats import wilcoxon_signed_rank  # noqa: E402

TAGS = ["low", "mid", "high", "funnel"]
TAG_TEX = {"low": r"\texttt{low}", "mid": r"\texttt{mid}",
           "high": r"\texttt{high}", "funnel": r"\texttt{funnel}"}

# 论文正文里的档位名;顺序按每次评价的成本从低到高,好让"越贵越差"一眼可见
ARM_TEX = {
    "twostage":          "two-stage (surrogate transport)",
    "opendispatch_nols": r"\textbf{evaluation loop} (proposed)",
    "opendispatch":      "+ contention-guided search",
    "nofeedback":        "+ reservation-aware dispatch",
    "nostagger":         "+ both, without staggering",
    "closed":            "+ both (full closed loop)",
    "priced":            "+ priced routing (control)",
}
ARM_ORDER = ["twostage", "opendispatch_nols", "opendispatch", "nofeedback",
             "nostagger", "closed", "priced"]

REF = "opendispatch_nols"      # 主方法:最小内核

# 消融表:每行只差一个因素。(机制, 上下文, 关掉的档, 开着的档)
CONTRASTS = [
    ("Conflict-free routing in the loop", "cheap dispatch",
     "twostage", "opendispatch_nols"),
    ("Conflict-free routing in the loop", "exact dispatch",
     "twostage", "nofeedback"),
    ("Reservation-aware dispatch", "no local search",
     "opendispatch_nols", "nofeedback"),
    ("Reservation-aware dispatch", "with local search",
     "opendispatch", "closed"),
    ("Contention-guided local search", "cheap dispatch",
     "opendispatch_nols", "opendispatch"),
    ("Contention-guided local search", "exact dispatch",
     "nofeedback", "closed"),
    ("Staggering operator", "on top of reassignment",
     "nostagger", "closed"),
    ("Priced routing", "on top of the full loop", "closed", "priced"),
]


def load(name):
    with open(os.path.join(DATA, name), encoding="utf-8") as f:
        return list(csv.DictReader(f))


def stars(p):
    """显著性星号。返回的是数学模式内的上标,故调用处须已在 $...$ 里。"""
    return "^{***}" if p < 1e-3 else "^{**}" if p < 1e-2 \
        else "^{*}" if p < 5e-2 else ""


def fmt_p(p):
    if p < 1e-4:
        return "$<10^{-4}$"
    if p >= 1e-3:
        return "%.3f" % p
    mant, exp = ("%.0e" % p).split("e")
    return r"$%s\times10^{%d}$" % (mant, int(exp))


def write(name, colspec, header, body):
    """写出**完整的** tabular 片段。

    片段必须自带 tabular 而不能只给表体:在 tabular 内部 \\input 一段以 `\\\\`
    结尾的文件会崩,因为 `\\\\` 需要向前扫描可选的 `[len]` 参数,而这个扫描跨不过
    文件边界,于是紧随的 \\bottomrule(展开为 \\noalign)不再紧接 \\cr。
    连带的好处是列格式与表头和生成表体待在一处,不会再各自漂移出列数不符。
    """
    path = os.path.join(HERE, name)
    lines = ["%% generated by tab/gen_tables.py -- do not edit by hand",
             r"\begin{tabular}{%s}" % colspec,
             r"\toprule",
             header.rstrip().rstrip("\\") + r" \\",
             r"\midrule",
             body.rstrip(),
             r"\bottomrule",
             r"\end{tabular}"]
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", os.path.relpath(path, ROOT))


# --------------------------------------------------------------------------


def table_instances(feats):
    """按拥堵档聚合:结构指标只取决于拥堵档,下界随 H 变,故给区间。"""
    rows = []
    for tag in TAGS:
        sub = [f for f in feats if f["congestion_tag"] == tag]
        if not sub:
            continue

        def uniq(key, cast=float):
            vals = sorted({cast(f[key]) for f in sub})
            return vals

        phi, cut, far = uniq("funnel_share"), uniq("lu_min_cut"), \
            uniq("far_group_cut")
        lb = uniq("lower_bound")
        nv, ne = uniq("num_nodes"), uniq("num_corridors")
        # 绑定项:三个下界分量里取到最大值的那个
        bind = set()
        for f in sub:
            terms = {"job chain": float(f["job_chain"]),
                     "machine load": float(f["machine_load"]),
                     "station cut": float(f["lu_cut"])}
            bind.add(max(terms, key=terms.get))

        def rng(vals, fmt="%.2f"):
            if len(vals) == 1:
                return fmt % vals[0]
            return (fmt + "--" + fmt) % (vals[0], vals[-1])

        rows.append(" & ".join([
            TAG_TEX[tag], rng(nv, "%.0f"), rng(ne, "%.0f"),
            rng(cut, "%.0f"), rng(far, "%.0f"), rng(phi),
            rng(lb, "%.1f"), ", ".join(sorted(bind)),
        ]) + r" \\")
    return "\n".join(rows)


def table_main(runs):
    """各档相对两阶段的收益,并列出每次评价的成本与实际完成的评价次数。"""
    idx = defaultdict(dict)
    for r in runs:
        idx[(r["instance"], r["seed"])][r["arm"]] = r
    cost, evals = defaultdict(list), defaultdict(list)
    for r in runs:
        if r.get("ms_per_eval"):
            cost[r["arm"]].append(float(r["ms_per_eval"]))
        if r.get("evaluations"):
            evals[r["arm"]].append(float(r["evaluations"]))

    rows = []
    for arm in ARM_ORDER:
        c = "%.2f" % st.mean(cost[arm]) if cost.get(arm) else "---"
        e = "%.0f" % st.mean(evals[arm]) if evals.get(arm) else "---"
        if arm == "twostage":
            rows.append(" & ".join([ARM_TEX[arm], c, e, "---", "---", "---"])
                        + r" \\")
            rows.append(r"\midrule")
            continue
        pairs = [(float(v["twostage"]["makespan"]), float(v[arm]["makespan"]))
                 for v in idx.values() if "twostage" in v and arm in v]
        g = 100 * st.mean([(a - b) / a for a, b in pairs if a > 0])
        w = wilcoxon_signed_rank([a for a, _ in pairs], [b for _, b in pairs])
        wins = sum(1 for a, b in pairs if b < a)
        loss = sum(1 for a, b in pairs if b > a)
        rows.append(" & ".join([
            ARM_TEX[arm], c, e,
            "$%+.2f%s$" % (g, stars(w["p_value"])),
            "%d/%d/%d" % (wins, loss, len(pairs) - wins - loss),
            fmt_p(w["p_value"]),
        ]) + r" \\")
    return "\n".join(rows)


def table_ablation(runs):
    """可归因的消融:每行只差一个因素,同一机制给两个上下文以便交叉核对。"""
    idx = defaultdict(dict)
    for r in runs:
        idx[(r["instance"], r["seed"])][r["arm"]] = r
    cost = defaultdict(list)
    for r in runs:
        if r.get("ms_per_eval"):
            cost[r["arm"]].append(float(r["ms_per_eval"]))

    rows, prev = [], None
    for mech, ctx, off, on in CONTRASTS:
        pairs = [(float(v[off]["makespan"]), float(v[on]["makespan"]))
                 for v in idx.values() if off in v and on in v]
        if not pairs:
            continue
        g = 100 * st.mean([(a - b) / a for a, b in pairs if a > 0])
        w = wilcoxon_signed_rank([a for a, _ in pairs], [b for _, b in pairs])
        wins = sum(1 for a, b in pairs if b < a)
        loss = sum(1 for a, b in pairs if b > a)
        ratio = st.mean(cost[on]) / st.mean(cost[off]) if cost.get(off) else 0
        if prev is not None and prev != mech:
            rows.append(r"\addlinespace")
        name = mech if prev != mech else ""
        prev = mech
        rows.append(" & ".join([
            name, ctx, r"$%.1f\times$" % ratio,
            "$%+.2f%s$" % (g, stars(w["p_value"])),
            "%d/%d/%d" % (wins, loss, len(pairs) - wins - loss),
            fmt_p(w["p_value"]),
        ]) + r" \\")
    return "\n".join(rows)


def table_bytag(runs):
    """主方法相对两阶段的收益,按拥堵档与异构度分层——用于'收益是否随拥堵上升'。"""
    idx = defaultdict(dict)
    for r in runs:
        idx[(r["instance"], r["seed"])][r["arm"]] = r
    rows = []
    for tag in TAGS:
        cells = []
        for het in ["0.0", "0.15", "0.3", "0.5"]:
            pairs = [(float(v["twostage"]["makespan"]), float(v[REF]["makespan"]))
                     for (i, _s), v in idx.items()
                     if "twostage" in v and REF in v
                     and v[REF]["tag"] == tag
                     and str(float(v[REF]["het"] or 0)) == het]
            cells.append("$%+.1f$" % (100 * st.mean(
                [(a - b) / a for a, b in pairs if a > 0])) if pairs else "---")
        pooled = [(float(v["twostage"]["makespan"]), float(v[REF]["makespan"]))
                  for v in idx.values()
                  if "twostage" in v and REF in v and v[REF]["tag"] == tag]
        w = wilcoxon_signed_rank([a for a, _ in pooled], [b for _, b in pooled])
        rows.append(" & ".join(
            [TAG_TEX[tag]] + cells
            + ["$%+.2f%s$" % (100 * st.mean([(a - b) / a for a, b in pooled
                                             if a > 0]), stars(w["p_value"]))]
        ) + r" \\")
    return "\n".join(rows)


def main() -> int:
    runs = load("runs.csv")
    feats = load("instances.csv")

    write("tab_instances.tex", "@{}lccccrrl@{}",
          r"Structure & $|V|$ & $|E|$ & cut & far cut & $\varphi$ & LB "
          r"& binding term",
          table_instances(feats))

    write("tab_main.tex", "@{}lrrrcr@{}",
          r"Configuration & ms/eval & evals & $\Delta C_{\max}$ (\%) "
          r"& W/L/T & $p$",
          table_main(runs))

    write("tab_ablation.tex", "@{}llrrcr@{}",
          r"Mechanism & Context & Cost & $\Delta C_{\max}$ (\%) & W/L/T & $p$",
          table_ablation(runs))

    write("tab_bytag.tex", "@{}lccccc@{}",
          r"& \multicolumn{4}{c}{$\Delta C_{\max}$ (\%) at $H=$} & pooled \\"
          "\n" r"\cmidrule(lr){2-5}" "\n"
          r"Structure & $0$ & $0.15$ & $0.3$ & $0.5$ & (\%)",
          table_bytag(runs))

    n_inst = len({r["instance"] for r in runs})
    n_seed = len({r["seed"] for r in runs})
    print("scope: %d instances x %d seeds, %d runs"
          % (n_inst, n_seed, len(runs)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
