# -*- coding: utf-8 -*-
"""The two main effects across the three factor families (Section 5.5).

Reads clbs/output/baseline_ladder.csv, the same file the tables and the preamble
macros come from, so the figure cannot drift from the prose.

What the figure has to make decidable: not "is the gain positive on average",
which the main table already answers, but "where does each mechanism stop
paying".  So both effects are drawn on one shared axis against the factor that
is varied, with zero marked, and cells where an effect changes sign are the
point of the picture rather than an embarrassment to be smoothed over.

The layout family has no natural numeric level, so it is plotted against
contention strength, which is what the layout manipulation actually changes.
The other two families are plotted against the level they vary, read out of the
case name -- the names are generated by tools/abc_matrix.py as "B NA/NM <v>"
and "C F=<v>", so the number in the name *is* the factor level by construction.

Run: py paper01/fig/fig_prediction3.py
"""
from __future__ import annotations

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from _style import (LADDER, by, load_output, mark_draft, mean,  # noqa: E402
                    plt, save)

HINT = "py -u -m tools.baseline_ladder --budget 90 --seeds 42,7,2024,13,1,99,123,777,31415,8"

# Effects shown.  Both are single-factor contrasts: each holds one factor of the
# 2x2 fixed and moves the other, so each can be attributed to one mechanism.
EFFECTS = [
    ("B0", "B1", "closed loop\n(rule dispatch fixed)", "#08519c", "o", "-"),
    ("B1", "B2", "probing dispatch\n(closed loop fixed)", "#d95f02", "s", "--"),
]
PANELS = [
    ("A", "layout", "contention strength (%)"),
    ("B", "fleet-to-arm ratio", "$N_A/N_M$"),
    ("C", "flexibility", "$F$"),
]


def level(case: str, family: str, cont: float) -> float:
    """The x position of a cell: its factor level, or contention for family A."""
    if family == "A":
        return 100.0 * cont
    m = re.search(r"([0-9]*\.?[0-9]+)\s*$", case)
    if not m:
        raise SystemExit("算例名 %r 末尾没有因子水平,无法定位横轴" % case)
    return float(m.group(1))


def main() -> None:
    rows = load_output("baseline_ladder.csv", HINT)
    seeds = sorted({r["seed"] for r in rows})
    cells = by(rows, "case")
    # The protocol of Section 5.1 commits to ten seeds; anything less is a
    # draft, and says so on its face rather than in a commit message.
    if len(seeds) < 10:
        mark_draft("%d seeds, protocol wants 10" % len(seeds))
    if len(cells) < 10:
        mark_draft("%d of 10 instance cells" % len(cells))

    fig, axes = plt.subplots(1, 3, figsize=(7.0, 2.35), sharey=True)
    for ax, (fam, fam_name, xlabel) in zip(axes, PANELS):
        names = [c for (c,) in cells if str(c).split()[0] == fam]
        if not names:
            ax.text(0.5, 0.5, "family %s absent" % fam, transform=ax.transAxes,
                    ha="center", va="center", fontsize=8, color="#999999")
            ax.set_xlabel(xlabel)
            continue
        cont = {c: cells[(c,)][0]["contention"] for c in names}
        names.sort(key=lambda c: level(c, fam, cont[c]))
        xs = [level(c, fam, cont[c]) for c in names]

        for ka, kb, label, colour, marker, ls in EFFECTS:
            ys = []
            for c in names:
                m = {a: mean([r["makespan"] for r in cells[(c,)]
                              if r["arm"] == a]) for a in LADDER}
                ys.append(100.0 * (m[kb] - m[ka]) / m[ka])
            ax.plot(xs, ys, ls, color=colour, marker=marker, markersize=4.2,
                    markeredgecolor="white", markeredgewidth=0.6,
                    label=label if fam == "A" else None, clip_on=False,
                    zorder=4)
            # A sign change is the substantive event in this figure, so it is
            # annotated rather than left for the reader to spot on the axis.
            for x, y in zip(xs, ys):
                if y > 0:
                    ax.annotate("harmful", (x, y), textcoords="offset points",
                                xytext=(0, 6), ha="center", fontsize=6.2,
                                color=colour, fontweight="bold")

        ax.axhline(0, color="#444444", linewidth=0.7, zorder=2)
        ax.set_xlabel(xlabel)
        ax.set_title("%s: %s" % (fam, fam_name), fontsize=8.5)
        if fam != "A":
            ax.set_xticks(xs)

    # Headroom for the "harmful" annotations, which sit above their points and
    # would otherwise be clipped by the panel title.
    lo, hi = axes[0].get_ylim()
    axes[0].set_ylim(lo, hi + 0.14 * (hi - lo))
    axes[0].set_ylabel("$\\Delta C_{\\max}$ (%)\nnegative is better")
    axes[0].legend(loc="lower left", fontsize=6.8, handlelength=1.8)
    fig.text(0.995, 0.015, "%d seeds per cell, equal wall clock" % len(seeds),
             ha="right", va="bottom", fontsize=6.2, color="#777777")
    fig.tight_layout()
    save(fig, "fig_prediction3")


if __name__ == "__main__":
    main()
